version: '3'


services:

  vuejs:
    build:
      context: .
      dockerfile: compose/local/vue2/Dockerfile
    image: qa_moderator_local_vuejs2
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "8080:8080"

