# Generated by Django 2.0.9 on 2018-10-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
