# Generated by Django 2.0.9 on 2018-10-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_historicalquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquestion',
            name='priority',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='question',
            name='priority',
            field=models.IntegerField(default=10000),
        ),
    ]
