# Generated by Django 2.0.9 on 2018-10-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20181007_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='moderator_num',
            field=models.IntegerField(default=0, help_text='Field to separate questions between moderators. Zero means not assigned'),
        ),
        migrations.AddField(
            model_name='question',
            name='moderator_num',
            field=models.IntegerField(default=0, help_text='Field to separate questions between moderators. Zero means not assigned'),
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='approved',
            field=models.BooleanField(default=False, help_text='Is approved to be displayed'),
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='priority',
            field=models.IntegerField(default=10000, help_text='Order to display questions. Lower number has higher priority and will be displayed first'),
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='viewed',
            field=models.BooleanField(default=False, help_text='Has already been displayed'),
        ),
        migrations.AlterField(
            model_name='question',
            name='approved',
            field=models.BooleanField(default=False, help_text='Is approved to be displayed'),
        ),
        migrations.AlterField(
            model_name='question',
            name='priority',
            field=models.IntegerField(default=10000, help_text='Order to display questions. Lower number has higher priority and will be displayed first'),
        ),
        migrations.AlterField(
            model_name='question',
            name='viewed',
            field=models.BooleanField(default=False, help_text='Has already been displayed'),
        ),
    ]
