# Generated by Django 2.2 on 2019-04-04 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('questions', '0005_auto_20181007_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.Event', verbose_name='event'),
        ),
        migrations.AddField(
            model_name='question',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.Event', verbose_name='event'),
        ),
    ]
